# Uncomment the next line to define a global platform for your project
platform :ios, '10.1'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FAITHNews

target 'FAITHNews' do

pod 'Kingfisher', '~> 3.2.1'
pod 'Alamofire', '~> 4.2.0'
end
